// Copies the compiled MandateAccount / MandateFactory ABIs from Foundry's `out/` into typed TS modules.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const outDir = resolve(import.meta.dirname, "../../../contracts/out");
for (const name of ["MandateAccount", "MandateFactory"]) {
  const artifact = JSON.parse(readFileSync(resolve(outDir, `${name}.sol/${name}.json`), "utf8"));
  const ts = `// AUTO-GENERATED by scripts/gen-abi.ts — do not edit.\nexport const ${name}Abi = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(resolve(import.meta.dirname, `../src/abi/${name}.ts`), ts);
  console.log(`wrote src/abi/${name}.ts (${artifact.abi.length} entries)`);
  if (name === "MandateAccount") {
    writeFileSync(resolve(import.meta.dirname, "../src/abi/MandateAccountBytecode.ts"), `// AUTO-GENERATED by scripts/gen-abi.ts — creation bytecode for CREATE2 address computation.\nexport const MandateAccountBytecode = ${JSON.stringify(artifact.bytecode.object)} as const;\n`);
    console.log("wrote src/abi/MandateAccountBytecode.ts");
  }
}
