import { spawn } from "node:child_process";
const cmd = process.argv[2] ?? "pnpm"; const args = process.argv[2] ? process.argv.slice(3) : ["exec", "tsx", "src/server.ts"];
const p = spawn(cmd, args, { cwd: process.cwd(), stdio: ["pipe", "pipe", "inherit"], env: { ...process.env, MANDATE_ENV_FILE: "../../.env" } });
let buf = "";
p.stdout.on("data", (d) => { buf += d.toString(); for (const line of buf.split("\n")) { if (!line.trim()) continue; try { const m = JSON.parse(line); if (m.id === 2) { console.log("tools:", m.result.tools.map((t) => t.name).join(", ")); p.kill(); process.exit(0); } } catch {} } });
const send = (o) => p.stdin.write(JSON.stringify(o) + "\n");
send({ jsonrpc: "2.0", id: 1, method: "initialize", params: { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "smoke", version: "0" } } });
send({ jsonrpc: "2.0", method: "notifications/initialized" });
setTimeout(() => send({ jsonrpc: "2.0", id: 2, method: "tools/list", params: {} }), 1500);
setTimeout(() => { console.error("timeout"); p.kill(); process.exit(1); }, 25000);
